landing/urls.py
from django.urls import path
from . import views

app_name = "landing"

urlpatterns = [
    path('', views.index, name='home'),
    path('submit/', views.submit, name='submit')
]

profilepage/urls.py
from django.urls import path
from . import views

app_name = "profile"
urlpatterns = [
    path('', views.index, name='profile')
]

tddjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('profile/', include('profilepage.urls')),
]

landing/models.py
from django.db import models

# Create your models here.


class Status(models.Model):
    status = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.status

profilepage/models.py
from django.db import models

# Create your models here.

landing/views.py
from django.shortcuts import render, redirect
from .models import Status

# Create your views here.


def index(request):
    status_list = Status.objects.all()
    return render(request, 'index.html', {'status': status_list})


def submit(request):
    if request.method == 'POST':
        stat = request.POST.get('input')
        if (0 < len(stat) <= 300):
            new_status = Status(status=stat)
            new_status.save()
        return redirect('landing:home')

profilepage/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'profile/index.html')

landing/templates/index.html
<!doctype html>
<html lang="en">

<head>
    {% load staticfiles %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Halo, apa Kabar</title>
</head>

<body>

    <div class="row p-5">
        <div class="col-lg-6 col-md-12 col-sm-12">
            <h1 class="header font-weight-bold">Halo, apa Kabar!</h1>
            <form action="{% url 'landing:submit' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <textarea class="form-control" id="input" rows="1" placeholder="How are you feeling today?"
                        name="input"></textarea>
                </div>
                <button class="btn btn-secondary" id="submit">Submit!</button>
            </form>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12 mt-3">
            <div class="output">
                {% for stat in status%}
                <div class="card text-white bg-secondary border-dark mb-3 mt-3">
                    <div class="card-header">{{ stat.created_at }}</div>
                    <div class="card-body text-white">
                        <p class="card-text">{{ stat }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

profilepage/templates/profile/index.html
<!DOCTYPE html>
<html>

<head>
    {% load staticfiles %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Jquery CSS -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'profile/style.css' %}">
    <title>Profile</title>
</head>

<body>
    <section class="row m-0">
        <div class="col-lg-6 col-md-12 col-sm-12 mb-5">
            <h1>Halo, Nama gw Huda!</h1>
            <a class="header">
                I am a Computer Science Undergrad Student at University Of Indonesia
                Technology have been my passion since i was little which led to my dream of pursuing my goal and
                career in this Industry.
                Background
                Started with my love for programming i took upon myself a few basic website projects a few years
                ago and found myself loving the abstraction and abnormality of what you call web development.
                Ever since then, i have been doing projects that revine my skills as a developer and continue to
                engage my knowledge in the IT world.
                <a class="mt-4" style="font-weight: bold">
                    This led me to applying and studying as a Computer Science student at the best CS faculty in
                    Indonesia. Meeting new amazing people. and learning a lot about Computer Programming.
                </a>
            </a>
        </div>
        <div class="col-lg-6 col-md-12 col-sm-12 mb-5">
            <div id="accordion">
                <h3>Daftar Aktifitas</h3>
                <div>
                    <p>
                        Berikut Daftar Aktivitas Mingguan di Semester 3:
                    </p>
                    <ul>
                        <p>Senin</p>
                        <li>10:00 - 11:40 ALIN</li>
                        <li>1:00 - 2:40 POK</li>
                    </ul>
                    <ul>
                        <p>Selasa</p>
                        <li>10:00 - 11:40 MATDAS</li>
                        <li>1:00 - 2:40 SDA</li>
                        <li>4:00 - 6:00 Lab SDA</li>
                        <li>6:00 - Kelar Rapat BEM</li>
                    </ul>
                    <ul>
                        <p>Rabu</p>
                        <li>9:00 - 9:50 ALIN</li>
                        <li>11:00 - 11:50 Fisdas</li>
                        <li>2:00 - 2:50 POK</li>
                        <li>3:00 - 4:00 Lab POK</li>
                    </ul>
                    <ul>
                        <p>Kamis</p>
                        <li>9:00 - 9:50 MATDAS</li>
                        <li>10:00 - 11:40 PPW</li>
                        <li>1:00 - 2:40 SDA</li>
                        <li>6:00 - Kelar Kelas SBF</li>
                    </ul>
                    <ul>
                        <p>Jumat</p>
                        <li>8:00 - 9:40 Lab PPW</li>
                        <li>10:00 - 11:40 Fisdas</li>
                    </ul>
                    <ul>
                        <p>Sabtu</p>
                        <li>Tidur
                        </li>
                    </ul>
                    <ul>
                        <p>Minggu</p>
                        <li>Tidur
                        </li>
                    </ul>
                </div>
                <h3>Pengalaman Organisasi dan Kepanitiaan</h3>
                <div>
                    <ul>
                        <li>Staff Open House Fasilkom - 2018</li>
                        <li>Staff IT developement Compfest X - 2019</li>
                        <li>Staff Bisnis dan Kemitraan BEM Fasilkom UI - 2019</li>
                    </ul>
                </div>
                <h3>Prestasi</h3>
                <div>
                    <p>Belum Ada</p>
                </div>
            </div>

        </div>
    </section>
    <ul id="but">
        <li>
            <span>Dark</span>
            <span>Light</span>
        </li>
    </ul>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
        integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>